import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";

import { routing } from "@/src/i18n/routing";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale} className={`${inter.variable} `}>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        {/* <meta name="image" property="og:image" content="/imageForSharing.jpg" />
        <meta name="twitter:image" content="/imageForSharing.jpg" />
        <meta name="robots" content="index, follow" /> */}
      </head>
      <body>
        <NextIntlClientProvider>
          <div className="flex min-h-screen flex-col">
            {/* <Header /> */}

            <main className="flex flex-[1_0_auto]">
              {children}
              {/* <Analytics /> */}
            </main>
            <footer className="bg-footer tab:pt-10 tab:pb-[43px] border-lightBorder flex-[0_0_auto] border-t px-4 pt-15 pb-16.25"></footer>
            {/* <Footer /> */}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
