import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";

import { Footer } from "@/src/components/footer/Footer";
import { Header } from "@/src/components/header/Header";
import { Background } from "@/src/components/shared/Background";
import { routing } from "@/src/i18n/routing";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale} className={inter.className}>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        {/* <meta name="image" property="og:image" content="/imageForSharing.jpg" />
        <meta name="twitter:image" content="/imageForSharing.jpg" />
        <meta name="robots" content="index, follow" /> */}
      </head>
      <body>
        <NextIntlClientProvider>
          <Background />
          <div className="flex min-h-screen flex-col">
            <Header />
            <main className="mt-[77px] flex flex-[1_0_auto] flex-col">
              {children}
              {/* <Analytics /> */}
            </main>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
